/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../objects/gameObject.ts" />
/// <reference path="../objects/vector2.ts" />
/// <reference path="../objects/bird.ts" />
/// <reference path="../objects/pie.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/mainGame.ts" />
/// <reference path="../scenes/tutorial.ts" /> 
//# sourceMappingURL=_reference.js.map