/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/node1.ts" />
/// <reference path="../scenes/node2c1.ts" />
/// <reference path="../scenes/node2c2.ts" />
/// <reference path="../scenes/node3c1.ts" />
/// <reference path="../scenes/node3c2.ts" />
/// <reference path="../scenes/node3c3.ts" />
/// <reference path="../scenes/node3c3Blk.ts" />
/// <reference path="../scenes/node3c4.ts" />
/// <reference path="../scenes/node4c1.ts" />
/// <reference path="../scenes/node4c2.ts" />
/// <reference path="../scenes/node4c3.ts" />
/// <reference path="../scenes/node4c4.ts" />
/// <reference path="../scenes/node4c5.ts" />
/// <reference path="../scenes/node4c6.ts" />
/// <reference path="../scenes/node4c7.ts" />
/// <reference path="../scenes/node4c8.ts" />
/// <reference path="../scenes/gameover.ts" /> 
//# sourceMappingURL=_reference.js.map